CVEs/cve_2015_0235.py
CVEs/cve_2016_5195.py
CVEs/cve_2017_1000405.py
CVEs/cve_2017_5715.py
CVEs/cve_2017_5753.py
CVEs/cve_2017_5754.py
CVEs/cve_2021_3177.py
CVEs/cve_2021_4034.py
CVEs/cve_2021_41773.py
CVEs/cve_2022_0847.py
CVEs/cve_2022_22965.py
CVEs/cve_2022_25636.py
CVEs/log4shell.py
CVEs/nimbuspwn.py
CVEs/shellshock.py
Modules/apache.py
Modules/commons.py
Modules/constants.py
Modules/docker_commands.py
Modules/get_pids.py
Modules/kernel_version.py
Modules/os_release.py
Modules/os_type.py
Modules/receive_package.py
Modules/run_command.py
README.md
am_i_really_vulnerable.py

- Added `is_supported_distribution` function
- Added  `check_linux_and_affected_distributions` function.

Merging Pylint Changes + Additional fixes

---

README.md

Add BlackHat 2022 badge and change the badges location in the Readme.md file.

Add blackhat badge and change badges location

---

cves/shellshock.py

Add missing pipe in the - CVE-2014-7187 exploit command

Fix CVE-2014-7187 exploit

---

cves/cve_2014_0160.py
cves/cve_2015_0235.py
cves/cve_2016_5195.py
cves/cve_2017_1000405.py
cves/cve_2017_5715.py
cves/cve_2017_5753.py
cves/cve_2017_5754.py
cves/cve_2020_1938.py
cves/cve_2021_3177.py
cves/cve_2021_4034.py
cves/cve_2021_41773.py
cves/cve_2022_0847.py
cves/cve_2022_22965.py
cves/cve_2022_25636.py
cves/log4shell.py
cves/nimbuspwn.py
cves/shellshock.py

Save the graphs as png instead of pdf
Change the CVE_ID variable name to VULNERABILITY

Save graph as png and change variables name

---

README.md
am_i_exploitable.py
cves/cve_2014_0160.py
cves/cve_2015_0235.py
cves/cve_2016_5195.py
cves/cve_2017_1000405.py
cves/cve_2017_5715.py
cves/cve_2017_5753.py
cves/cve_2017_5754.py
cves/cve_2020_1938.py
cves/cve_2021_3177.py
cves/cve_2021_4034.py
cves/cve_2021_41773.py
cves/cve_2022_0847.py
cves/cve_2022_22965.py
cves/cve_2022_25636.py
cves/log4shell.py
cves/nimbuspwn.py
cves/shellshock.py
modules/commons.py
modules/docker_commands.py
modules/get_pids.py
modules/kernel_version.py

Change parameters names.
Fix places in code that used boolean instead of str.
Handle boolean parameters because argparse does not handle it correctly.
Add support for specifying containers names to be scanned.

Argparse fixes

---

cves/cve_2021_41773.py
modules/apache.py

There was a map between distributions and apache commands, now for each distributions, each command will be checked.
Split to functions.

Fix for apache vulnerability and apache module

---

README.md

reflects updated input parameter names

Update execution gif

---

cves/cve_2021_4154.py
cves/cve_2022_2588.py
modules/kernel_version.py

Fix the two cves
On CVE-2022-2588 - Add the kernel version check and change condition
On CVE-2021_4154 - Change condition
kernel_version - Add check if the kernel version ends with '/n'

Fix dirty cred

---

cves/cve_2021_4154.py
cves/cve_2022_2588.py
modules/kernel_version.py

Fix the two cves
On CVE-2022-2588 - Add the kernel version check and change condition
On CVE-2021_4154 - Change condition
kernel_version - Add check if the kernel version ends with '/n'

Fix Dirty_Cred

---

am_i_exploitable.py
cves/cve_2014_0160.py
cves/cve_2015_0235.py
cves/cve_2016_5195.py
cves/cve_2017_1000405.py
cves/cve_2017_5715.py
cves/cve_2017_5753.py
cves/cve_2017_5754.py
cves/cve_2020_1938.py
cves/cve_2021_3177.py
cves/cve_2021_4034.py
cves/cve_2021_4154.py
cves/cve_2021_41773.py
cves/cve_2022_0847.py
cves/cve_2022_22965.py
cves/cve_2022_25636.py
cves/cve_2022_2588.py
cves/log4shell.py
cves/nimbuspwn.py
cves/shellshock.py
modules/commons.py
modules/constants.py
modules/os_release.py
modules/output_format.py
modules/status.py
modules/supported.py

Add the report_format parameter.
Add support for machine readable output - json, csv and text

Format parameter

---

cves/cve_2021_3177.py
cves/cve_2022_22965.py
cves/log4shell.py
modules/process_functions.py

Create process version function inside new process_function module

Process version

---

cves/cve_2021_3177.py
cves/spookyssl.py
modules/commons.py
modules/constants.py
modules/docker_commands.py
modules/kernel_version.py
modules/process_functions.py

Create spookyssl.py
Change the file_content function in commons.py to not print the process
Change the order of debug and container_name in docker_commands.py
Add spookyssl to constants.py
Add functions to process_functions.py and change functions
Add check to the regex in kernel_version.py

Openssl vulnerability

---

README.md
cves/spookyssl.py
modules/process_functions.py

Change the two methods (two and three) to one that checks if the running processes loaded files and executable files are loading an affected OpenSSL version

Spookyssl add checks

---

cves/spookyssl.py
modules/file_functions.py
modules/process_functions.py

Add check to spookyssl.py if the detected file is using the affected OpenSSL dynamically and load so file that uses it or if it is using it statically and compiled with the affected OpenSSL code and print it out as a conclusion message

Change spookyssl

---

am_i_exploitable.py
modules/output_format.py

Change the parameters order and remove the use of the file_exists module

Format fixes

---

README.md
am_i_exploitable.py
cves/cve_2014_0160.py
cves/spookyssl.py
modules/constants.py
modules/supported_environment_functions.py

Add windows support for the heartbleed vulnerability.
Add relevant information about the Windows support in the README file

Heardbleed windows support

---

README.md
am_i_exploitable.py
cves/cve_2014_0160.py
cves/cve_2015_0235.py
cves/cve_2017_1000405.py
cves/cve_2021_3177.py
cves/cve_2021_4034.py
cves/cve_2022_22965.py
cves/log4shell.py
cves/nimbuspwn.py
cves/shellshock.py
cves/spookyssl.py
modules/apache_functions.py
modules/constants.py
modules/docker_functions.py
modules/file_functions.py
modules/java_functions.py
modules/kernel_functions.py
modules/os_release_functions.py
modules/package_functions.py
modules/process_functions.py
modules/supported_environment_functions.py
modules/version_functions.py

Changes according to Amit's code review

Code review 01

---

cves/cve_2021_41773.py
modules/apache_functions.py
modules/file_functions.py

Add support when the configuration file is not placed in the default location

---

cves/cve_2021_41773.py
modules/apache_functions.py

Check if the configuration file meets all vulnerable configurations
Change the check of the loaded modules 
Change mitigation recommendations

Add checks to CVE 2021 41173

---

README.md
cves/cve_2021_41773.py
modules/apache_functions.py

Check if the configuration file meets all vulnerable configurations
Change the check of the loaded modules 
Change mitigation recommendations

Add checks to CVE-2021-41173
